Created sceleton of chat window dock & chat window itself
cpp-lv425/PairStormIDE pull request #14
Opened 2019-07-25 12:33 UTC by vsakharevych

2019-07-25 14:01 UTC, DANIV18 requested changes
MainWindow should call method to place docker.

2019-07-25 14:10 UTC, DANIV18 approved these changes

2019-07-25 14:56 UTC, MarsLviv approved these changes

2019-07-25 15:34 UTC, merged

2019-07-28 06:59 UTC, FedorenkoAndriy commented on src/mainwindow/mainwindow.cpp
> +//    QString dirName = QFileDialog::getExistingDirectory
Please don't comment code. You can use git history for this purpose