terminal & git inside pair storm
cpp-lv425/PairStormIDE pull request #86
Opened 2019-09-09 08:12 UTC by PeterLysyk

2019-09-09 08:37 UTC, opastushkov requested changes

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/bottompaneldock.cpp
> +#include <QDebug>
Remove qDebug

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consoleserviceprovider.cpp
> +#include <QDebug>
Remove qDebug

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consoleserviceprovider.cpp
> +#include <QtCore>
QtCore is too huge. Include only useful modules.

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consoleserviceprovider.cpp
> +    if (QSysInfo::productType() == windowsProductType)// if it's windows console
Use one comment style.

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consoleserviceprovider.cpp
> +    executionCommand +=command;
```executionCommand += command;```

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/bottompaneldock.h
> +    void reSendProjectPathChanged(QString);
```void resendProjectPathChanged(QString);```

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consoleliterals.h
> +#include <QString>
You included QString and don't use it.

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consolewindow.cpp
> +    QGridLayout *consoleViewGridLayout = new QGridLayout (this);
```QGridLayout *consoleViewGridLayout = new QGridLayout(this);```

2019-09-09 08:37 UTC, opastushkov commented on src/bottompanel/consolewindow/consolewindow.h
> +class ConsoleWindow;
Add tab

2019-09-09 08:37 UTC, opastushkov commented on src/mainwindow/mainwindow.h
> +    //QScopedPointer<DocumentManager> mpDocumentManager;
Remove commented code.

2019-09-13 08:47 UTC, PeterLysyk commented on src/bottompanel/consolewindow/consoleserviceprovider.cpp
> +    if (QSysInfo::productType() == windowsProductType)// if it's windows console
What did you mean?

2019-09-13 08:49 UTC, PeterLysyk commented on src/bottompanel/consolewindow/consolewindow.h
> +class ConsoleWindow;
QT generated this by itself

2019-09-13 09:53 UTC, closed without merging